apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate ConfigMaps wrapping the OpenAPI and AsyncAPI
# files. API CR expects a configmap with 
# the API definition, this lets us keep the API definitions in source format.
configMapGenerator:
  - name: nginx-config
    files:
      - default.conf.template

generatorOptions:
  disableNameSuffixHash: true

resources:
  - nginx-deployment.yaml
  - buildconfig.yaml