apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-eem
spec:
  selector:
    matchLabels:
      app: nginx-proxy-eem
  template:
    metadata:
      labels:
        app: nginx-proxy-eem
    spec:
      containers:
      - name: nginx-proxy
        image: image-registry.openshift-image-registry.svc:5000/cp4i/nginx:latest
        ports:
        - containerPort: 9443
          name: http
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/templates/default.conf.template 
          subPath: default.conf.template
        - name: certificates
          mountPath: /etc/nginx/default.conf/
        env:
        - name: EEM_TOKEN
          valueFrom:
            secretKeyRef:
              name: eem-token-secret 
              key: eem-token  
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: certificates
        secret: 
          secretName: nginx-server-cert-secret