# Certificate for internal native ha communication
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-server-cert
spec:
  secretTemplate:
    annotations:
      cert-utils-operator.redhat-cop.io/generate-cert-info: "true"
  secretName: nginx-server-cert-secret
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - 'nginx'
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  dnsNames:
    - 'localhost'
    - '*.cp4i.svc'
    - '*.cp4i.svc.local'
    - '*.cp4i.svc.local.cluster'
  issuerRef:
    name: selfsigned-issuer
